package ca.bc.gov.educ.api.edx.constants;

public enum EventOutcome {
  PEN_REQUEST_UPDATED,
  PEN_REQUEST_FOUND,
  PEN_REQUEST_NOT_FOUND,
  PEN_REQUEST_COMMENT_ADDED,
  PEN_REQUEST_COMMENT_ALREADY_EXIST,
  PEN_REQUEST_DOCUMENTS_FOUND,
  PEN_REQUEST_DOCUMENTS_NOT_FOUND,
}
