package ca.bc.gov.educ.api.edx.constants;

public enum EventType {
  UPDATE_PEN_REQUEST,
  GET_PEN_REQUEST, PEN_REQUEST_EVENT_OUTBOX_PROCESSED, ADD_PEN_REQUEST_COMMENT,
  GET_PEN_REQUEST_DOCUMENT_METADATA
}
