package ca.bc.gov.educ.api.edx.constants;

/**
 * The enum Topics enum.
 */
public enum TopicsEnum {

  EDX_SCHOOL_USER_ACTIVATION_INVITE_TOPIC,

  /**
   * Edx new secure exchange topic topics enum.
   */
  EDX_NEW_SECURE_EXCHANGE_TOPIC,

  EDX_SCHOOL_USER_ACTIVATION_RELINK_TOPIC,

  EDX_DISTRICT_USER_ACTIVATION_RELINK_TOPIC,

  /**
   * Edx secure exchange comment topic topics enum.
   */
  EDX_SECURE_EXCHANGE_COMMENT_TOPIC,
  EDX_DISTRICT_USER_ACTIVATION_INVITE_TOPIC,
  EDX_MOVE_SCHOOL_TOPIC,
  EDX_CREATE_SCHOOL_TOPIC,
  EDX_ONBOARD_SCHOOL_USER_TOPIC,
  EDX_ONBOARD_DISTRICT_USER_TOPIC,
  EDX_EVENT_TOPIC,
  INSTITUTE_API_TOPIC,
  INSTITUTE_EVENTS_TOPIC

}
