INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('SCH_GRAD_RO', 'School GRAD Read-Only', 'GRAD read-only permission for School.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('VIEW_SCH_GRAD_RPT', 'View School GRAD Reports', 'GRAD view reports permission for School.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('DIS_GRAD_RO', 'District GRAD Read-Only', 'GRAD read-only permission for District.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('VIEW_DIS_GRAD_RPT', 'View District GRAD Reports', 'GRAD view reports permission for District.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('SCH_GRAD_RO', 'School GRAD Read-Only', FALSE, 'Read-only GRAD role for School.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('DIS_GRAD_RO', 'District GRAD Read-Only', TRUE, 'Read-only GRAD role for District.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'SCH_GRAD_RO', 'SCH_GRAD_RO', 'IDIR/AVSODHI',
        to_date('2024-10-01', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-10-01', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'SCH_GRAD_RO', 'EDX_SCHOOL_VIEW', 'IDIR/AVSODHI',
        to_date('2024-10-01', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-10-01', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'SCH_GRAD_RO', 'VIEW_SCH_GRAD_RPT', 'IDIR/AVSODHI',
        to_date('2024-10-01', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-10-01', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'DIS_GRAD_RO', 'DIS_GRAD_RO', 'IDIR/AVSODHI',
        to_date('2024-10-01', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-10-01', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'DIS_GRAD_RO', 'EDX_SCHOOL_VIEW', 'IDIR/AVSODHI',
        to_date('2024-10-01', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-10-01', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'DIS_GRAD_RO', 'EDX_DISTRICT_VIEW', 'IDIR/AVSODHI',
        to_date('2024-10-01', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-10-01', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'DIS_GRAD_RO', 'VIEW_DIS_GRAD_RPT', 'IDIR/AVSODHI',
        to_date('2024-10-01', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-10-01', 'YYYY-MM-DD'));