ALTER TABLE EDX_USER_DISTRICT
    ADD CONSTRAINT EDX_USER_ID_DISTRICT_ID_UK UNIQUE (EDX_USER_ID, DISTRICT_ID);

ALTER TABLE EDX_USER_DISTRICT_ROLE
    ADD CONSTRAINT EDX_USER_DISTRICT_ID_EDX_ROLE_UK UNIQUE (EDX_USER_DISTRICT_ID, EDX_ROLE_CODE);



