ALTER TABLE EDX_MINISTRY_OWNERSHIP_TEAM
ADD COLUMN DESCRIPTION VARCHAR(255);

UPDATE EDX_MINISTRY_OWNERSHIP_TEAM
SET DESCRIPTION='Responsible for updating student demographic data and resolving issues with a student’s PEN.'
WHERE GROUP_ROLE_IDENTIFIER='PEN_TEAM_ROLE';