ALTER TABLE EDX_ROLE ALTER COLUMN LABEL TYPE VARCHAR(40);

UPDATE EDX_ROLE
SET LABEL = 'Graduation Data Administrator'
WHERE EDX_ROLE_CODE = 'GRAD_SCH_ADMIN';

UPDATE EDX_ROLE
SET LABEL = 'Graduation Data Administrator'
WHERE EDX_ROLE_CODE = 'GRAD_DIS_ADMIN';

UPDATE EDX_ROLE
SET LABEL = 'Enrolment Data Collection Viewer'
WHERE EDX_ROLE_CODE = 'DIS_SDC_RO';

UPDATE EDX_ROLE
SET LABEL = 'Enrolment Data Collection Viewer'
WHERE EDX_ROLE_CODE = 'SCH_SDC_RO';

UPDATE EDX_ROLE
SET LABEL = 'Enrolment Data Collection Administrator'
WHERE EDX_ROLE_CODE = 'SCHOOL_SDC';

UPDATE EDX_ROLE
SET LABEL = 'Enrolment Data Collection Administrator'
WHERE EDX_ROLE_CODE = 'DISTRICT_SDC';

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_SCH_RO', 'Graduation Data Viewer', FALSE, 'Graduation Data Viewer', 'IDIR/MVILLENE', 'IDIR/MVILLENE');

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_DIS_RO', 'Graduation Data Viewer', TRUE, 'Graduation Data Viewer', 'IDIR/MVILLENE', 'IDIR/MVILLENE');

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_RO', 'GRAD_SCH_TVR_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_RO', 'GRAD_SCH_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_RO', 'GRAD_ERR_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_RO', 'EDX_SCHOOL_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'GRAD_SCH_TVR_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'GRAD_SCH_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'GRAD_ERR_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'EDX_SCHOOL_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'EDX_DISTRICT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'GRAD_DIS_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'GRAD_DIS_TVR_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'EAS_DIS_EDIT', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'EAS_SCH_EDIT', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'EAS_SCH_EDIT', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

DELETE FROM EDX_ROLE_PERMISSION WHERE EDX_ROLE_CODE = 'EAS_SCH_ADMIN';

DELETE FROM EDX_ROLE_PERMISSION WHERE EDX_ROLE_CODE = 'EAS_DIS_ADMIN';

DELETE FROM edx_user_school_role WHERE EDX_ROLE_CODE = 'EAS_SCH_ADMIN';

DELETE FROM edx_user_district_role WHERE EDX_ROLE_CODE = 'EAS_DIS_ADMIN';

DELETE FROM edx_activation_role WHERE EDX_ROLE_CODE = 'EAS_SCH_ADMIN';

DELETE FROM edx_activation_role WHERE EDX_ROLE_CODE = 'EAS_DIS_ADMIN';

DELETE FROM EDX_ROLE WHERE EDX_ROLE_CODE = 'EAS_SCH_ADMIN';

DELETE FROM EDX_ROLE WHERE EDX_ROLE_CODE = 'EAS_DIS_ADMIN';

