INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('SECURE_EXCHANGE_SCHOOL', 'Secure Exchange', false, 'Secure exchange role.', 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'SECURE_EXCHANGE_SCHOOL', 'SECURE_EXCHANGE', 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

UPDATE EDX_ACTIVATION_ROLE
SET EDX_ROLE_CODE = 'SECURE_EXCHANGE_SCHOOL'
WHERE EDX_ROLE_CODE = 'SECURE_EXCHANGE';

UPDATE EDX_USER_SCHOOL_ROLE
SET EDX_ROLE_CODE = 'SECURE_EXCHANGE_SCHOOL'
WHERE EDX_ROLE_CODE = 'SECURE_EXCHANGE';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SECURE_EXCHANGE';

DELETE FROM EDX_ROLE
WHERE EDX_ROLE_CODE = 'SECURE_EXCHANGE';

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('SECURE_EXCHANGE_DISTRICT', 'Secure Exchange', true, 'Secure exchange role.', 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'SECURE_EXCHANGE_DISTRICT', 'SECURE_EXCHANGE', 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));