INSERT INTO EDX_ROLE (EDX_ROLE_CODE, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE,
                      LABEL)
VALUES ('EDX_SCHOOL_ADMIN', true, 'EDX School Administrator Role', 'IDIR/SRATH',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/SRATH', to_date('2019-11-07', 'YYYY-MM-DD'),
        'EDX School Administrator');

UPDATE EDX_ROLE_PERMISSION
SET EDX_ROLE_CODE = 'EDX_SCHOOL_ADMIN'
WHERE EDX_ROLE_CODE = 'EDX_ADMIN';

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('EDX_USER_SCHOOL_ADMIN', 'EDX User School Administrator', 'EDX User School Permission.', 'IDIR/SRATH',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/SRATH', to_date('2019-11-07', 'YYYY-MM-DD'));

UPDATE EDX_ROLE_PERMISSION
SET edx_permission_code = 'EDX_USER_SCHOOL_ADMIN'
WHERE edx_permission_code = 'EDX_USER_ADMIN';

UPDATE EDX_ACTIVATION_ROLE
SET EDX_ROLE_CODE = 'EDX_SCHOOL_ADMIN'
WHERE EDX_ROLE_CODE = 'EDX_ADMIN';

UPDATE EDX_USER_SCHOOL_ROLE
SET EDX_ROLE_CODE = 'EDX_SCHOOL_ADMIN'
WHERE EDX_ROLE_CODE = 'EDX_ADMIN';

DELETE
FROM EDX_ROLE
WHERE EDX_ROLE_CODE = 'EDX_ADMIN';

DELETE
FROM EDX_PERMISSION
WHERE EDX_PERMISSION_CODE = 'EDX_USER_ADMIN';

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE,
                      LABEL)
VALUES ('EDX_DISTRICT_ADMIN', true, 'EDX District Admin Role', 'IDIR/SRATH',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/SRATH', to_date('2019-11-07', 'YYYY-MM-DD'),
        'EDX District Administrator');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('EDX_USER_DISTRICT_ADMIN', 'EDX User District Admin', 'EDX User Administrator Permission.',
        'IDIR/SRATH',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/SRATH', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_DISTRICT_ADMIN', 'SECURE_EXCHANGE', 'IDIR/SRATH',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/SRATH', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_DISTRICT_ADMIN', 'EDX_USER_DISTRICT_ADMIN', 'IDIR/SRATH',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/SRATH', to_date('2019-11-07', 'YYYY-MM-DD'));
