DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'GRAD_SCH_ADMIN' AND EDX_PERMISSION_CODE = 'GRAD_SCH_EDIT';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'GRAD_DIS_ADMIN' AND EDX_PERMISSION_CODE = 'GRAD_DIS_EDIT';

DELETE FROM EDX_PERMISSION
WHERE EDX_PERMISSION_CODE = 'GRAD_SCH_EDIT';

DELETE FROM EDX_PERMISSION
WHERE EDX_PERMISSION_CODE = 'GRAD_SCH_EDIT';

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_SCH_UPLOAD', 'GRAD School Upload', 'GRAD upload files for School.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_DIS_UPLOAD', 'GRAD District Upload', 'GRAD upload files for District.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_ERR_RPT_VIEW', 'GRAD Error Report View', 'GRAD view error reports', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'GRAD_SCH_UPLOAD', 'IDIR/AVSODHI',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'GRAD_ERR_RPT_VIEW', 'IDIR/AVSODHI',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'GRAD_DIS_UPLOAD', 'IDIR/AVSODHI',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'GRAD_ERR_RPT_VIEW', 'IDIR/AVSODHI',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-01-31', 'YYYY-MM-DD'));