INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('EDX_SCHOOL_EDIT', 'EDX School Edit', 'Permission to edit school details and contacts.', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('EDX_DISTRICT_EDIT', 'EDX District Edit', 'Permission to edit district details and contacts.', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

UPDATE EDX_PERMISSION
SET LABEL = 'District User Administrator', DESCRIPTION = 'Permission for administering EDX District users.'
WHERE EDX_PERMISSION_CODE = 'EDX_USER_DISTRICT_ADMIN';

UPDATE EDX_PERMISSION
SET LABEL = 'School User Administrator', DESCRIPTION = 'Permission for administering EDX School users.'
WHERE EDX_PERMISSION_CODE = 'EDX_USER_SCHOOL_ADMIN';

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('EDX_EDIT_SCHOOL', 'Edit School', false, 'Edit school role.', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('EDX_EDIT_DISTRICT', 'Edit District', true, 'Edit district role.', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_EDIT_SCHOOL', 'EDX_SCHOOL_EDIT', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_SCHOOL_ADMIN', 'EDX_SCHOOL_EDIT', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_EDIT_DISTRICT', 'EDX_SCHOOL_EDIT', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_EDIT_DISTRICT', 'EDX_DISTRICT_EDIT', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_DISTRICT_ADMIN', 'EDX_DISTRICT_EDIT', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_DISTRICT_ADMIN', 'EDX_SCHOOL_EDIT', 'IDIR/JOHCOX', CURRENT_TIMESTAMP, 'IDIR/JOHCOX', CURRENT_TIMESTAMP);