DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'GRAD_SCH_ADMIN' AND EDX_PERMISSION_CODE = 'GRAD_SCH_EDIT';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'GRAD_DIS_ADMIN' AND EDX_PERMISSION_CODE = 'GRAD_DIS_EDIT';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'GRAD_SCH_ADMIN' AND EDX_PERMISSION_CODE = 'EDX_SCHOOL_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'GRAD_DIS_ADMIN' AND EDX_PERMISSION_CODE = 'EDX_SCHOOL_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'GRAD_DIS_ADMIN' AND EDX_PERMISSION_CODE = 'EDX_DISTRICT_VIEW';

DELETE FROM EDX_PERMISSION
WHERE EDX_PERMISSION_CODE = 'GRAD_SCH_EDIT';

DELETE FROM EDX_PERMISSION
WHERE EDX_PERMISSION_CODE = 'GRAD_DIS_EDIT';

DELETE FROM EDX_ROLE
WHERE EDX_ROLE_CODE = 'GRAD_DIS_ADMIN';

DELETE FROM EDX_ROLE
WHERE EDX_ROLE_CODE = 'GRAD_SCH_ADMIN';
