UPDATE SECURE_EXCHANGE_STATUS_CODE SET LABEL='New' WHERE SECURE_EXCHANGE_STATUS_CODE ='NEW';
DELETE FROM SECURE_EXCHANGE_STATUS_CODE WHERE SECURE_EXCHANGE_STATUS_CODE ='CLOSED';

INSERT INTO SECURE_EXCHANGE_STATUS_CODE (SECURE_EXCHANGE_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                         EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                         UPDATE_DATE)
VALUES ('COMPLETE', 'Complete', 'Secure exchange completed.', 3,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));



