CREATE TABLE PEN_RETRIEVAL_REQUEST_EVENT
(
    EVENT_ID      RAW(16)                             NOT NULL,
    EVENT_PAYLOAD VARCHAR(4000)                       NOT NULL,
    EVENT_STATUS  VARCHAR2(50)                        NOT NULL,
    EVENT_TYPE    VARCHAR2(100)                       NOT NULL,
    SAGA_ID       RAW(16),
    EVENT_OUTCOME VARCHAR2(100)                       NOT NULL,
    REPLY_CHANNEL VARCHAR2(100),
    CREATE_USER   VARCHAR(32)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(32)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PEN_RETRIEVAL_REQUEST_EVENT_PK PRIMARY KEY (EVENT_ID)
);
CREATE INDEX PEN_RETRIEVAL_REQUEST_EVENT_EVENT_STATUS_IDX ON PEN_RETRIEVAL_REQUEST_EVENT (EVENT_STATUS) TABLESPACE API_PEN_RETRIEVAL_IDX;
CREATE INDEX PEN_RETRIEVAL_REQUEST_EVENT_SAGA_ID_IDX ON PEN_RETRIEVAL_REQUEST_EVENT (SAGA_ID) TABLESPACE API_PEN_RETRIEVAL_IDX;
CREATE INDEX PEN_RETRIEVAL_REQUEST_EVENT_EVENT_TYPE_IDX ON PEN_RETRIEVAL_REQUEST_EVENT (EVENT_TYPE) TABLESPACE API_PEN_RETRIEVAL_IDX;


CREATE TABLE PEN_RETRIEVAL_REQUEST_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    PRIMARY KEY (NAME)
);
COMMENT ON TABLE PEN_RETRIEVAL_REQUEST_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

INSERT INTO PEN_RETRIEVAL_REQUEST_STATUS_CODE (PEN_RETRIEVAL_REQUEST_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                               EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                               UPDATE_DATE)
VALUES ('ABANDONED', 'Abandoned', 'email not verified within 1 week.', 8,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/GRCHWELO',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/GRCHWELO', to_date('2019-11-07', 'YYYY-MM-DD'));