ALTER TABLE EDX_USER_SCHOOL
    ADD COLUMN EXPIRY_DATE TIMESTAMP;

ALTER TABLE EDX_USER_DISTRICT
    ADD COLUMN EXPIRY_DATE TIMESTAMP;

ALTER TABLE EDX_ACTIVATION_CODE
    ADD COLUMN EDX_USER_EXPIRY_DATE TIMESTAMP;
