UPDATE EDX_ROLE
SET LABEL = 'Graduation Data Administrator'
WHERE EDX_ROLE_CODE = 'GRAD_SCH_ADMIN';

UPDATE EDX_ROLE
SET LABEL = 'Graduation Data Administrator'
WHERE EDX_ROLE_CODE = 'GRAD_DIS_ADMIN';

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_SCH_RO', 'Graduation Data Viewer', FALSE, 'Graduation Data Viewer', 'IDIR/MVILLENE', 'IDIR/MVILLENE');

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_DIS_RO', 'Graduation Data Viewer', TRUE, 'Graduation Data Viewer', 'IDIR/MVILLENE', 'IDIR/MVILLENE');

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'GRAD_SCH_TVR_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'GRAD_SCH_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'GRAD_ERR_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'EDX_SCHOOL_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'GRAD_SCH_TVR_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'GRAD_SCH_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'GRAD_ERR_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'EDX_SCHOOL_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'EDX_DISTRICT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'GRAD_DIS_RPT_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'GRAD_DIS_TVR_VIEW', 'IDIR/MVILLENE',
        to_date('2025-01-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2025-01-31', 'YYYY-MM-DD'));


