INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('EAS_SCH_VIEW', 'School Assessment View', 'School Assessment View',
        'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('EAS_DIS_VIEW', 'District Assessment View', 'District Assessment View',
        'IDIR/AVSODHI', 'IDIR/AVSODHI');


INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_RO', 'EAS_SCH_VIEW', 'IDIR/AVSODHI',
        to_date('2025-09-02', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-09-02', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'EAS_DIS_VIEW', 'IDIR/AVSODHI',
        to_date('2025-09-02', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-09-02', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'EAS_SCH_VIEW', 'IDIR/AVSODHI',
        to_date('2025-09-02', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-09-02', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'EAS_DIS_VIEW', 'IDIR/AVSODHI',
        to_date('2025-09-02', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-09-02', 'YYYY-MM-DD'));