DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SECR_TRES' AND EDX_PERMISSION_CODE = 'DIS_SDC_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SECR_TRES' AND EDX_PERMISSION_CODE = 'SECR_TRES';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SECR_TRES' AND EDX_PERMISSION_CODE = 'EDX_SCHOOL_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SECR_TRES' AND EDX_PERMISSION_CODE = 'EDX_DISTRICT_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SECR_TRES' AND EDX_PERMISSION_CODE = 'SCH_SDC_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SUPERINT' AND EDX_PERMISSION_CODE = 'SUPERINT';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SUPERINT' AND EDX_PERMISSION_CODE = 'EDX_SCHOOL_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SUPERINT' AND EDX_PERMISSION_CODE = 'EDX_DISTRICT_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SUPERINT' AND EDX_PERMISSION_CODE = 'DIS_SDC_VIEW';

DELETE FROM EDX_ROLE_PERMISSION
WHERE EDX_ROLE_CODE = 'SUPERINT' AND EDX_PERMISSION_CODE = 'SCH_SDC_VIEW';

DELETE FROM EDX_PERMISSION
WHERE EDX_PERMISSION_CODE = 'SUPERINT';

DELETE FROM EDX_PERMISSION
WHERE EDX_PERMISSION_CODE = 'SECR_TRES';

DELETE FROM EDX_ROLE
WHERE EDX_ROLE_CODE = 'SECR_TRES';

DELETE FROM EDX_ROLE
WHERE EDX_ROLE_CODE = 'SUPERINT';
