ALTER TABLE EDX_USER_SCHOOL
    ADD CONSTRAINT EDX_USER_ID_SCHOOL_ID_UK UNIQUE (EDX_USER_ID, SCHOOL_ID);

ALTER TABLE EDX_USER_SCHOOL_ROLE
    ADD CONSTRAINT EDX_USER_SCHOOL_ID_EDX_ROLE_UK UNIQUE (EDX_USER_SCHOOL_ID, EDX_ROLE_CODE);



