INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('CHALLENGE_REPORTS', 'Challenge Reports View', 'Permission to view Challenge Reports',
        'IDIR/EECKERMA', 'IDIR/EECKERMA');


INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'DISTRICT_SDC', 'CHALLENGE_REPORTS', 'IDIR/EECKERMA',
        to_date('2025-05-26', 'YYYY-MM-DD'), 'IDIR/EECKERMA', to_date('2025-05-26', 'YYYY-MM-DD'));