INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_ADMIN', 'EAS_SCH_VIEW', 'IDIR/AVSODHI',
        to_date('2025-09-02', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-09-02', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_DIS_RO', 'EAS_SCH_VIEW', 'IDIR/AVSODHI',
        to_date('2025-09-02', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2025-09-02', 'YYYY-MM-DD'));