ALTER TABLE EDX_ACTIVATION_CODE
    ADD COLUMN first_name VARCHAR(255) NOT NULL,
    ADD COLUMN last_name  VARCHAR(255) NOT NULL,
    ADD COLUMN email      VARCHAR(255) NOT NULL;


TRUNCATE TABLE EDX_USER
    CASCADE;

ALTER TABLE EDX_USER
    ADD COLUMN email VARCHAR(255) NOT NULL;

