ALTER TABLE EDX_ACTIVATION_CODE ALTER COLUMN FIRST_NAME DROP NOT NULL;
ALTER TABLE EDX_ACTIVATION_CODE ALTER COLUMN LAST_NAME DROP NOT NULL;
ALTER TABLE EDX_ACTIVATION_CODE ALTER COLUMN EMAIL DROP NOT NULL;