INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('EAS_SCH_ADMIN', 'Assessment Administrator', FALSE, 'Assessment Administrator.', 'IDIR/STHIRUMA', 'IDIR/STHIRUMA');

INSERT INTO EDX_ROLE (EDX_ROLE_CODE, LABEL, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('EAS_DIS_ADMIN', 'Assessment Administrator', TRUE, 'Assessment Administrator.', 'IDIR/STHIRUMA', 'IDIR/STHIRUMA');


INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('EAS_SCH_EDIT', 'EAS School Edit', 'EAS edit permission for School.', 'IDIR/STHIRUMA', 'IDIR/STHIRUMA');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('EAS_DIS_EDIT', 'EAS District Edit', 'EAS edit permission for District.', 'IDIR/STHIRUMA', 'IDIR/STHIRUMA');


INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EAS_SCH_ADMIN', 'EAS_SCH_EDIT', 'IDIR/STHIRUMA',
        to_date('2024-11-08', 'YYYY-MM-DD'), 'IDIR/STHIRUMA', to_date('2024-11-08', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EAS_SCH_ADMIN', 'EDX_SCHOOL_VIEW', 'IDIR/STHIRUMA',
        to_date('2024-11-08', 'YYYY-MM-DD'), 'IDIR/STHIRUMA', to_date('2024-11-08', 'YYYY-MM-DD'));


INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EAS_DIS_ADMIN', 'EAS_DIS_EDIT', 'IDIR/STHIRUMA',
        to_date('2024-11-08', 'YYYY-MM-DD'), 'IDIR/STHIRUMA', to_date('2024-11-08', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EAS_DIS_ADMIN', 'EDX_SCHOOL_VIEW', 'IDIR/STHIRUMA',
        to_date('2024-11-08', 'YYYY-MM-DD'), 'IDIR/STHIRUMA', to_date('2024-11-08', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EAS_DIS_ADMIN', 'EDX_DISTRICT_VIEW', 'IDIR/STHIRUMA',
        to_date('2024-11-08', 'YYYY-MM-DD'), 'IDIR/STHIRUMA', to_date('2024-11-08', 'YYYY-MM-DD'));