CREATE EXTENSION pgcrypto;
CREATE SEQUENCE SEC_EXCHANGE_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 99999999 CYCLE CACHE 10;
CREATE TABLE SECURE_EXCHANGE
(
    SECURE_EXCHANGE_ID                UUID                 NOT NULL,
    SECURE_EXCHANGE_CONTACT_TYPE_CODE VARCHAR(10)         NOT NULL,
    EDX_MINISTRY_OWNERSHIP_TEAM_ID    UUID                 NOT NULL,
    CONTACT_IDENTIFIER                VARCHAR(255),
    SECURE_EXCHANGE_STATUS_CODE       VARCHAR(10)         NOT NULL,
    REVIEWER                          VARCHAR(255),
    IS_READ_BY_MINISTRY               BOOLEAN              NOT NULL,
    IS_READ_BY_CONTACT                BOOLEAN              NOT NULL,
    SUBJECT                           VARCHAR(4000)       NOT NULL,
    STATUS_UPDATE_TIMESTAMP           DATE                 NOT NULL,
    SEQUENCE_NUMBER                   NUMERIC               DEFAULT nextval('SEC_EXCHANGE_SEQ') NOT NULL,
    CREATE_USER                       VARCHAR(32)         NOT NULL,
    CREATE_DATE                       DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER                       VARCHAR(32)         NOT NULL,
    UPDATE_DATE                       DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT SECURE_EXCHANGE_ID_PK PRIMARY KEY (SECURE_EXCHANGE_ID)
);

CREATE TABLE SECURE_EXCHANGE_CONTACT_TYPE_CODE
(
    SECURE_EXCHANGE_CONTACT_TYPE_CODE VARCHAR(10)           NOT NULL,
    LABEL                             VARCHAR(30),
    DESCRIPTION                       VARCHAR(255),
    DISPLAY_ORDER                     NUMERIC DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE                    DATE                   NOT NULL,
    EXPIRY_DATE                       DATE                   NOT NULL,
    CREATE_USER                       VARCHAR(32)           NOT NULL,
    CREATE_DATE                       DATE   DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER                       VARCHAR(32)           NOT NULL,
    UPDATE_DATE                       DATE   DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT SECURE_EXCHANGE_CONTACT_TYPE_CODE_PK PRIMARY KEY (SECURE_EXCHANGE_CONTACT_TYPE_CODE)
);

CREATE TABLE SECURE_EXCHANGE_STATUS_CODE
(
    SECURE_EXCHANGE_STATUS_CODE VARCHAR(10)           NOT NULL,
    LABEL                       VARCHAR(30),
    DESCRIPTION                 VARCHAR(255),
    DISPLAY_ORDER               NUMERIC DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE              DATE                   NOT NULL,
    EXPIRY_DATE                 DATE                   NOT NULL,
    CREATE_USER                 VARCHAR(32)           NOT NULL,
    CREATE_DATE                 DATE   DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER                 VARCHAR(32)           NOT NULL,
    UPDATE_DATE                 DATE   DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT SECURE_EXCHANGE_STATUS_CODE_PK PRIMARY KEY (SECURE_EXCHANGE_STATUS_CODE)
);

CREATE TABLE SECURE_EXCHANGE_DOCUMENT_TYPE_CODE
(
    SECURE_EXCHANGE_DOCUMENT_TYPE_CODE VARCHAR(10)           NOT NULL,
    LABEL                              VARCHAR(30),
    DESCRIPTION                        VARCHAR(255),
    DISPLAY_ORDER                      NUMERIC DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE                     DATE                   NOT NULL,
    EXPIRY_DATE                        DATE                   NOT NULL,
    CREATE_USER                        VARCHAR(32)           NOT NULL,
    CREATE_DATE                        DATE   DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER                        VARCHAR(32)           NOT NULL,
    UPDATE_DATE                        DATE   DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT SECURE_EXCHANGE_DOCUMENT_TYPE_CODE_PK PRIMARY KEY (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE)
);

CREATE TABLE EDX_PERMISSION
(
    EDX_PERMISSION_ID UUID                NOT NULL,
    NAME              VARCHAR(30)         NOT NULL,
    DESCRIPTION       VARCHAR(255)        NOT NULL,
    CREATE_USER       VARCHAR(32)         NOT NULL,
    CREATE_DATE       DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER       VARCHAR(32)         NOT NULL,
    UPDATE_DATE       DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_PERMISSION_ID_PK PRIMARY KEY (EDX_PERMISSION_ID)
);

CREATE TABLE EDX_USER_SCHOOL
(
    EDX_USER_SCHOOL_ID UUID                 NOT NULL,
    MINCODE            VARCHAR(8)          NOT NULL,
    EDX_USER_ID        UUID                 NOT NULL,
    CREATE_USER        VARCHAR(32)         NOT NULL,
    CREATE_DATE        DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER        VARCHAR(32)         NOT NULL,
    UPDATE_DATE        DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_USER_SCHOOL_ID_PK PRIMARY KEY (EDX_USER_SCHOOL_ID)
);

CREATE TABLE EDX_USER_DISTRICT
(
    EDX_USER_DISTRICT_ID UUID                 NOT NULL,
    DISTRICT_CODE        VARCHAR(3)          NOT NULL,
    EDX_USER_ID          UUID                 NOT NULL,
    CREATE_USER          VARCHAR(32)         NOT NULL,
    CREATE_DATE          DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER          VARCHAR(32)         NOT NULL,
    UPDATE_DATE          DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_USER_DISTRICT_ID_PK PRIMARY KEY (EDX_USER_DISTRICT_ID)
);

CREATE TABLE EDX_ROLE_PERMISSION
(
    EDX_ROLE_PERMISSION_ID UUID                 NOT NULL,
    EDX_ROLE_ID            UUID                 NOT NULL,
    EDX_PERMISSION_ID      UUID                 NOT NULL,
    CREATE_USER            VARCHAR(32)         NOT NULL,
    CREATE_DATE            DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER            VARCHAR(32)         NOT NULL,
    UPDATE_DATE            DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_ROLE_PERMISSION_ID_PK PRIMARY KEY (EDX_ROLE_PERMISSION_ID)
);

CREATE TABLE EDX_ROLE
(
    EDX_ROLE_ID      UUID                 NOT NULL,
    NAME             VARCHAR(30)         NOT NULL,
    IS_DISTRICT_ROLE VARCHAR(1)          NOT NULL,
    DESCRIPTION      VARCHAR(255)        NOT NULL,
    CREATE_USER      VARCHAR(32)         NOT NULL,
    CREATE_DATE      DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER      VARCHAR(32)         NOT NULL,
    UPDATE_DATE      DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_ROLE_ID_PK PRIMARY KEY (EDX_ROLE_ID)
);

CREATE TABLE EDX_USER
(
    EDX_USER_ID         UUID                 NOT NULL,
    FIRST_NAME          VARCHAR(255)        NOT NULL,
    LAST_NAME           VARCHAR(255)        NOT NULL,
    DIGITAL_IDENTITY_ID UUID                 NOT NULL,
    CREATE_USER         VARCHAR(32)         NOT NULL,
    CREATE_DATE         DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER         VARCHAR(32)         NOT NULL,
    UPDATE_DATE         DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_USER_ID_PK PRIMARY KEY (EDX_USER_ID)
);

CREATE TABLE EDX_USER_SCHOOL_ROLE
(
    EDX_USER_SCHOOL_ROLE_ID UUID                 NOT NULL,
    EDX_USER_SCHOOL_ID      UUID                 NOT NULL,
    EDX_ROLE_ID             UUID                 NOT NULL,
    CREATE_USER             VARCHAR(32)         NOT NULL,
    CREATE_DATE             DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER             VARCHAR(32)         NOT NULL,
    UPDATE_DATE             DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_USER_SCHOOL_ROLE_ID_PK PRIMARY KEY (EDX_USER_SCHOOL_ROLE_ID)
);

CREATE TABLE EDX_USER_DISTRICT_ROLE
(
    EDX_USER_DISTRICT_ROLE_ID UUID                 NOT NULL,
    EDX_USER_DISTRICT_ID      UUID                 NOT NULL,
    EDX_ROLE_ID               UUID                 NOT NULL,
    CREATE_USER               VARCHAR(32)         NOT NULL,
    CREATE_DATE               DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER               VARCHAR(32)         NOT NULL,
    UPDATE_DATE               DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_USER_DISTRICT_ROLE_ID_PK PRIMARY KEY (EDX_USER_DISTRICT_ROLE_ID)
);

CREATE TABLE EDX_ACTIVATION_CODE
(
    EDX_ACTIVATION_CODE_ID UUID                 NOT NULL,
    MINCODE                VARCHAR(8),
    DISTRICT_CODE          VARCHAR(3),
    ACTIVATION_CODE        VARCHAR(10)         NOT NULL,
    IS_PRIMARY             VARCHAR(1)          NOT NULL,
    EXPIRY_DATE            DATE                 NOT NULL,
    CREATE_USER            VARCHAR(32)         NOT NULL,
    CREATE_DATE            DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER            VARCHAR(32)         NOT NULL,
    UPDATE_DATE            DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_ACTIVATION_CODE_ID_PK PRIMARY KEY (EDX_ACTIVATION_CODE_ID)
);

CREATE TABLE EDX_ACTIVATION_ROLE
(
    EDX_ACTIVATION_ROLE_ID UUID                 NOT NULL,
    EDX_ACTIVATION_CODE_ID UUID                 NOT NULL,
    EDX_ROLE_ID            UUID                 NOT NULL,
    CREATE_USER            VARCHAR(32)         NOT NULL,
    CREATE_DATE            DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER            VARCHAR(32)         NOT NULL,
    UPDATE_DATE            DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_ACTIVATION_ROLE_ID_PK PRIMARY KEY (EDX_ACTIVATION_ROLE_ID)
);

CREATE TABLE EDX_MINISTRY_OWNERSHIP_TEAM
(
    EDX_MINISTRY_OWNERSHIP_TEAM_ID UUID                 NOT NULL,
    TEAM_NAME                      VARCHAR(255)        NOT NULL,
    GROUP_ROLE_IDENTIFIER          VARCHAR(255)        NOT NULL,
    CREATE_USER                    VARCHAR(32)         NOT NULL,
    CREATE_DATE                    DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER                    VARCHAR(32)         NOT NULL,
    UPDATE_DATE                    DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT EDX_MINISTRY_OWNERSHIP_TEAM_ID_PK PRIMARY KEY (EDX_MINISTRY_OWNERSHIP_TEAM_ID)
);

CREATE TABLE SECURE_EXCHANGE_COMMENT
(
    SECURE_EXCHANGE_COMMENT_ID UUID                 NOT NULL,
    SECURE_EXCHANGE_ID         UUID                 NOT NULL,
    EDX_USER_ID                UUID,
    STAFF_USER_IDENTIFIER      VARCHAR(255),
    COMMENT_USER_NAME          VARCHAR(255)        NOT NULL,
    COMMENT_CONTENT            VARCHAR(4000)       NOT NULL,
    COMMENT_TIMESTAMP          DATE                 NOT NULL,
    CREATE_USER                VARCHAR(32)         NOT NULL,
    CREATE_DATE                DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER                VARCHAR(32)         NOT NULL,
    UPDATE_DATE                DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT SECURE_EXCHANGE_COMMENT_ID_PK PRIMARY KEY (SECURE_EXCHANGE_COMMENT_ID)
);

CREATE TABLE SECURE_EXCHANGE_NOTE
(
    SECURE_EXCHANGE_NOTE_ID UUID                 NOT NULL,
    SECURE_EXCHANGE_ID      UUID                 NOT NULL,
    STAFF_USER_IDENTIFIER   VARCHAR(255)        NOT NULL,
    STAFF_USER_NAME         VARCHAR(255)        NOT NULL,
    NOTE_CONTENT            VARCHAR(4000)       NOT NULL,
    NOTE_TIMESTAMP          DATE                 NOT NULL,
    CREATE_USER             VARCHAR(32)         NOT NULL,
    CREATE_DATE             DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER             VARCHAR(32)         NOT NULL,
    UPDATE_DATE             DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT SECURE_EXCHANGE_NOTE_ID_PK PRIMARY KEY (SECURE_EXCHANGE_NOTE_ID)
);

CREATE TABLE SECURE_EXCHANGE_DOCUMENT
(
    SECURE_EXCHANGE_DOCUMENT_ID        UUID                 NOT NULL,
    SECURE_EXCHANGE_ID                 UUID                 NOT NULL,
    SECURE_EXCHANGE_DOCUMENT_TYPE_CODE VARCHAR(10)         NOT NULL,
    FILE_NAME                          VARCHAR(255)        NOT NULL,
    FILE_EXTENSION                     VARCHAR(255),
    FILE_SIZE                          NUMERIC,
    DOCUMENT_DATA                      BYTEA,
    EDX_USER_ID                        UUID,
    STAFF_USER_IDENTIFIER              UUID,
    CREATE_USER                        VARCHAR(32)         NOT NULL,
    CREATE_DATE                        DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER                        VARCHAR(32)         NOT NULL,
    UPDATE_DATE                        DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT SECURE_EXCHANGE_DOCUMENT_PK PRIMARY KEY (SECURE_EXCHANGE_DOCUMENT_ID)
);

ALTER TABLE EDX_USER_SCHOOL
    ADD CONSTRAINT FK_EDX_USER_SCHOOL_EDX_USER_ID FOREIGN KEY (EDX_USER_ID) REFERENCES EDX_USER (EDX_USER_ID);

ALTER TABLE EDX_USER_DISTRICT
    ADD CONSTRAINT FK_EDX_USER_DISTRICT_EDX_USER_ID FOREIGN KEY (EDX_USER_ID) REFERENCES EDX_USER (EDX_USER_ID);

ALTER TABLE EDX_ROLE_PERMISSION
    ADD CONSTRAINT FK_EDX_ROLE_PERMISSION_EDX_ROLE_ID FOREIGN KEY (EDX_ROLE_ID) REFERENCES EDX_ROLE (EDX_ROLE_ID);
ALTER TABLE EDX_ROLE_PERMISSION
    ADD CONSTRAINT FK_EDX_ROLE_PERMISSION_EDX_PERMISSION_ID FOREIGN KEY (EDX_PERMISSION_ID) REFERENCES EDX_PERMISSION (EDX_PERMISSION_ID);

ALTER TABLE EDX_USER_DISTRICT_ROLE
    ADD CONSTRAINT FK_EDX_USER_DISTRICT_ROLE_EDX_USER_DISTRICT_ID FOREIGN KEY (EDX_USER_DISTRICT_ID) REFERENCES EDX_USER_DISTRICT (EDX_USER_DISTRICT_ID);
ALTER TABLE EDX_USER_DISTRICT_ROLE
    ADD CONSTRAINT FK_EDX_USER_DISTRICT_ROLE_EDX_ROLE_ID FOREIGN KEY (EDX_ROLE_ID) REFERENCES EDX_ROLE (EDX_ROLE_ID);
ALTER TABLE EDX_USER_SCHOOL_ROLE
    ADD CONSTRAINT FK_EDX_USER_SCHOOL_ROLE_EDX_USER_SCHOOL_ID FOREIGN KEY (EDX_USER_SCHOOL_ID) REFERENCES EDX_USER_SCHOOL (EDX_USER_SCHOOL_ID);
ALTER TABLE EDX_USER_SCHOOL_ROLE
    ADD CONSTRAINT FK_EDX_USER_SCHOOL_ROLE_EDX_ROLE_ID FOREIGN KEY (EDX_ROLE_ID) REFERENCES EDX_ROLE (EDX_ROLE_ID);

ALTER TABLE EDX_ACTIVATION_ROLE
    ADD CONSTRAINT FK_EDX_ACTIVATION_ROLE_EDX_ROLE_ID FOREIGN KEY (EDX_ROLE_ID) REFERENCES EDX_ROLE (EDX_ROLE_ID);
ALTER TABLE EDX_ACTIVATION_ROLE
    ADD CONSTRAINT FK_EDX_ACTIVATION_ROLE_EDX_ACTIVATION_CODE_ID FOREIGN KEY (EDX_ACTIVATION_CODE_ID) REFERENCES EDX_ACTIVATION_CODE (EDX_ACTIVATION_CODE_ID);

ALTER TABLE SECURE_EXCHANGE_COMMENT
    ADD CONSTRAINT FK_SECURE_EXCHANGE_COMMENT_SECURE_EXCHANGE_ID FOREIGN KEY (SECURE_EXCHANGE_ID) REFERENCES SECURE_EXCHANGE (SECURE_EXCHANGE_ID);
ALTER TABLE SECURE_EXCHANGE_COMMENT
    ADD CONSTRAINT FK_SECURE_EXCHANGE_COMMENT_EDX_USER_ID FOREIGN KEY (EDX_USER_ID) REFERENCES EDX_USER (EDX_USER_ID);

ALTER TABLE SECURE_EXCHANGE_NOTE
    ADD CONSTRAINT FK_SECURE_EXCHANGE_NOTE_SECURE_EXCHANGE_ID FOREIGN KEY (SECURE_EXCHANGE_ID) REFERENCES SECURE_EXCHANGE (SECURE_EXCHANGE_ID);

ALTER TABLE SECURE_EXCHANGE_DOCUMENT
    ADD CONSTRAINT FK_SECURE_EXCHANGE_DOCUMENT_SECURE_EXCHANGE_ID FOREIGN KEY (SECURE_EXCHANGE_ID) REFERENCES SECURE_EXCHANGE (SECURE_EXCHANGE_ID);
ALTER TABLE SECURE_EXCHANGE_DOCUMENT
    ADD CONSTRAINT FK_SECURE_EXCHANGE_DOCUMENT_SECURE_EXCHANGE_DOCUMENT_TYPE_CODE FOREIGN KEY (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE) REFERENCES SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE);
ALTER TABLE SECURE_EXCHANGE_DOCUMENT
    ADD CONSTRAINT FK_SECURE_EXCHANGE_DOCUMENT_EDX_USER_ID FOREIGN KEY (EDX_USER_ID) REFERENCES EDX_USER (EDX_USER_ID);

ALTER TABLE SECURE_EXCHANGE
    ADD CONSTRAINT FK_SECURE_EXCHANGE_SECURE_EXCHANGE_STATUS_CODE FOREIGN KEY (SECURE_EXCHANGE_STATUS_CODE) REFERENCES SECURE_EXCHANGE_STATUS_CODE (SECURE_EXCHANGE_STATUS_CODE);
ALTER TABLE SECURE_EXCHANGE
    ADD CONSTRAINT FK_SECURE_EXCHANGE_EDX_MINISTRY_OWNERSHIP_TEAM_ID FOREIGN KEY (EDX_MINISTRY_OWNERSHIP_TEAM_ID) REFERENCES EDX_MINISTRY_OWNERSHIP_TEAM (EDX_MINISTRY_OWNERSHIP_TEAM_ID);
ALTER TABLE SECURE_EXCHANGE
    ADD CONSTRAINT FK_SECURE_EXCHANGE_SECURE_EXCHANGE_CONTACT_TYPE_CODE FOREIGN KEY (SECURE_EXCHANGE_CONTACT_TYPE_CODE) REFERENCES SECURE_EXCHANGE_CONTACT_TYPE_CODE (SECURE_EXCHANGE_CONTACT_TYPE_CODE);

INSERT INTO SECURE_EXCHANGE_STATUS_CODE (SECURE_EXCHANGE_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                         EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                         UPDATE_DATE)
VALUES ('NEW', 'New exchange', 'New secure exchange.', 1,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_STATUS_CODE (SECURE_EXCHANGE_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                         EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                         UPDATE_DATE)
VALUES ('INPROG', 'In Progress', 'Secure exchange in progress.', 2,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_STATUS_CODE (SECURE_EXCHANGE_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                         EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                         UPDATE_DATE)
VALUES ('CLOSED', 'Closed exchange', 'Closed secure exchange.', 3,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_CONTACT_TYPE_CODE (SECURE_EXCHANGE_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                               EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                               UPDATE_DATE)
VALUES ('EDXUSER', 'EDX User', 'EDX User ID type.', 1,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_CONTACT_TYPE_CODE (SECURE_EXCHANGE_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                               EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                               UPDATE_DATE)
VALUES ('SCHOOL', 'School', 'School type using mincode.', 2,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_CONTACT_TYPE_CODE (SECURE_EXCHANGE_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                               EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                               UPDATE_DATE)
VALUES ('DISTRICT', 'District', 'District type using district code.', 3,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_CONTACT_TYPE_CODE (SECURE_EXCHANGE_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                               EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                               UPDATE_DATE)
VALUES ('MINTEAM', 'Ministry Team', 'Ministry team type.', 4,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('CABIRTH', 'Canadian Birth Certificate', 'Canadian Birth Certificate', 10,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('CAPASSPORT', 'Canadian Passport', 'Canadian Passport', 20,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('CADL', 'Canadian Driver''s Licence', 'Canadian Driver''s Licence', 30,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('BCIDCARD', 'Provincial Identification Card', 'Provincial Identification Card', 40,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('BCSCPHOTO', 'BC Services Card w Photo', 'BC Services Card (Photo version only)', 50,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('CACITZCARD', 'Canadian Citizenship Card', 'Canadian Citizenship Card', 60,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('PRCARD', 'Permanent Residence Card', 'Permanent Residence Card', 70,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('STUDENTPMT', 'Student / Study Permit', 'Student / Study Permit', 80,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('IMM5292', 'IMM5292 Conf of Perm Residence', 'Confirmation of Permanent Residence (IMM5292)', 90,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('IMM1000', 'IMM1000 Record of Landing',
        'Canadian Immigration Record of Landing (IMM 1000, not valid after June 2002)', 100,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('INDSTATUS', 'Indian Status Card', 'Indian Status Card', 110,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('NAMECHANGE', 'Legal Name Change document', 'Canadian court order approving legal change of name', 120,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('FORPASSPRT', 'Foreign Passport', 'Foreign Passport', 130,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('ADOPTION', 'Canadian adoption order', 'Canadian adoption order', 140,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('MARRIAGE', 'Marriage Certificate', 'Marriage Certificate', 150,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('FORBIRTH', 'Foreign Birth Certificate', 'Foreign Birth Certificate (with English translation)', 160,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SECURE_EXCHANGE_DOCUMENT_TYPE_CODE (SECURE_EXCHANGE_DOCUMENT_TYPE_CODE, LABEL, DESCRIPTION,
                                                DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                                CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('OTHER', 'Other', 'Other document type', 170, to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO EDX_MINISTRY_OWNERSHIP_TEAM (EDX_MINISTRY_OWNERSHIP_TEAM_ID, TEAM_NAME, GROUP_ROLE_IDENTIFIER,
                                         CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'PEN', 'PEN_TEAM_ROLE', 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

CREATE INDEX SECURE_EXCHANGE_EDX_USER_DISTRICT_ID_I ON SECURE_EXCHANGE (CONTACT_IDENTIFIER);
CREATE INDEX SECURE_EXCHANGE_EDX_MINISTRY_OWNERSHIP_TEAM_ID_I ON SECURE_EXCHANGE (EDX_MINISTRY_OWNERSHIP_TEAM_ID);
CREATE INDEX SECURE_EXCHANGE_COMMENT_SECURE_EXCHANGE_ID_I ON SECURE_EXCHANGE_COMMENT (SECURE_EXCHANGE_ID);
CREATE INDEX SECURE_EXCHANGE_DOCUMENT_SECURE_EXCHANGE_ID_I ON SECURE_EXCHANGE_DOCUMENT (SECURE_EXCHANGE_ID);


