ALTER TABLE EDX_USER_SCHOOL
    ADD CONSTRAINT EDX_USER_ID_MINCODE_UK UNIQUE (EDX_USER_ID, MINCODE);

ALTER TABLE EDX_USER_SCHOOL_ROLE
    ADD CONSTRAINT EDX_USER_SCHOOL_ID_EDX_ROLE_UK UNIQUE (EDX_USER_SCHOOL_ID, EDX_ROLE_ID);



