INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_SCH_TVR_VIEW', 'GRAD School TVR View', 'GRAD view projections and tvrs reports permission for School.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_PERMISSION (EDX_PERMISSION_CODE, LABEL, DESCRIPTION, CREATE_USER, UPDATE_USER)
VALUES ('GRAD_SCH_RPT_VIEW', 'GRAD School Reports View', 'GRAD view reports and transcripts permission for School.', 'IDIR/AVSODHI', 'IDIR/AVSODHI');

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'GRAD_SCH_TVR_VIEW', 'IDIR/AVSODHI',
        to_date('2024-11-18', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-11-18', 'YYYY-MM-DD'));

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'GRAD_SCH_ADMIN', 'GRAD_SCH_RPT_VIEW', 'IDIR/AVSODHI',
        to_date('2024-11-18', 'YYYY-MM-DD'), 'IDIR/AVSODHI', to_date('2024-11-18', 'YYYY-MM-DD'));