ALTER TABLE EDX_USER_DISTRICT
DROP COLUMN DISTRICT_CODE ;

ALTER TABLE EDX_USER_DISTRICT
    ADD COLUMN DISTRICT_ID UUID ;

ALTER TABLE EDX_ACTIVATION_CODE
DROP COLUMN DISTRICT_CODE ;

ALTER TABLE EDX_ACTIVATION_CODE
    ADD COLUMN DISTRICT_ID UUID ;
