INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'STUDENT_DATA_COLLECTION', 'EDX_USER_SCHOOL_ADMIN', 'IDIR/HKOHLI', CURRENT_TIMESTAMP, 'IDIR/HKOHLI', CURRENT_TIMESTAMP);
