INSERT INTO EDX_ROLE (EDX_ROLE_CODE, IS_DISTRICT_ROLE, DESCRIPTION, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE, LABEL)
VALUES ('EDX_ADMIN', false, 'EDX administrator role.', 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'), 'EDX Administrator');

INSERT INTO EDX_ROLE_PERMISSION (EDX_ROLE_PERMISSION_ID, EDX_ROLE_CODE, EDX_PERMISSION_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (gen_random_uuid(), 'EDX_ADMIN', 'SECURE_EXCHANGE', 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));