INSERT INTO SECURE_EXCHANGE_STATUS_CODE (SECURE_EXCHANGE_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                         EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                         UPDATE_DATE)
VALUES ('OPEN', 'Open exchange', 'Open secure exchange.', 1,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO SECURE_EXCHANGE_STATUS_CODE (SECURE_EXCHANGE_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                         EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                         UPDATE_DATE)
VALUES ('CLOSED', 'Closed Exchange', 'Closed secure exchange.', 2,
        to_date('2020-01-01', 'YYYY-MM-DD'), to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'), 'IDIR/MVILLENE', to_date('2019-11-07', 'YYYY-MM-DD'));

UPDATE SECURE_EXCHANGE
SET SECURE_EXCHANGE_STATUS_CODE = 'OPEN'
WHERE SECURE_EXCHANGE_STATUS_CODE in ('NEW', 'INPROG');

UPDATE SECURE_EXCHANGE
SET SECURE_EXCHANGE_STATUS_CODE = 'CLOSED'
WHERE SECURE_EXCHANGE_STATUS_CODE in ('COMPLETE');

DELETE FROM SECURE_EXCHANGE_STATUS_CODE
WHERE SECURE_EXCHANGE_STATUS_CODE in ('NEW', 'INPROG', 'COMPLETE');