CREATE TABLE EDX_SAGA
(
    SAGA_ID            UUID                                NOT NULL,
    SAGA_NAME          VARCHAR(50)                         NOT NULL,
    SAGA_STATE         VARCHAR(100)                        NOT NULL,
    PAYLOAD            VARCHAR                             NOT NULL,
    RETRY_COUNT        INTEGER,
    STATUS             VARCHAR(20)                         NOT NULL,
    SAGA_COMPENSATED   BOOLEAN                             NOT NULL,
    EMAIL_ID           VARCHAR(255),
    SCHOOL_ID          UUID,
    EDX_USER_ID        UUID,
    SECURE_EXCHANGE_ID UUID,
    CREATE_USER        VARCHAR(32)                         NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER        VARCHAR(32)                         NOT NULL,
    UPDATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT EDX_SAGA_PK PRIMARY KEY (SAGA_ID)
);

CREATE INDEX EDX_SAGA_STATUS_IDX ON EDX_SAGA (STATUS);
CREATE INDEX EDX_SAGA_EMAIL_ID_IDX ON EDX_SAGA (EMAIL_ID);
CREATE INDEX EDX_SAGA_SCHOOL_ID_IDX ON EDX_SAGA (SCHOOL_ID);
CREATE INDEX EDX_SAGA_EDX_USER_ID_IDX ON EDX_SAGA (EDX_USER_ID);
CREATE INDEX EDX_SAGA_SECURE_EXCHANGE_ID_IDX ON EDX_SAGA (SECURE_EXCHANGE_ID);

CREATE TABLE EDX_SAGA_EVENT_STATES
(
    SAGA_EVENT_ID       UUID                                NOT NULL,
    SAGA_ID             UUID                                NOT NULL,
    SAGA_EVENT_STATE    VARCHAR(100)                        NOT NULL,
    SAGA_EVENT_OUTCOME  VARCHAR(100)                        NOT NULL,
    SAGA_STEP_NUMBER    INTEGER                             NOT NULL,
    SAGA_EVENT_RESPONSE VARCHAR                             NOT NULL,
    CREATE_USER         VARCHAR(32)                         NOT NULL,
    CREATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER         VARCHAR(32)                         NOT NULL,
    UPDATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT EDX_SAGA_EVENT_STATES_PK PRIMARY KEY (SAGA_EVENT_ID)
);

ALTER TABLE EDX_SAGA_EVENT_STATES
    ADD CONSTRAINT EDX_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES EDX_SAGA (SAGA_ID);
CREATE INDEX EDX_SAGA_EVENT_STATES_SID_SES_SEO_SSN_IDX ON EDX_SAGA_EVENT_STATES (SAGA_ID, SAGA_EVENT_STATE, SAGA_EVENT_OUTCOME, SAGA_STEP_NUMBER);
