ALTER TABLE EDX_ACTIVATION_CODE ALTER COLUMN EXPIRY_DATE DROP NOT NULL;
ALTER TABLE EDX_ACTIVATION_CODE ALTER COLUMN VALIDATION_CODE DROP NOT NULL;
ALTER TABLE EDX_ACTIVATION_CODE ALTER COLUMN IS_URL_CLICKED DROP NOT NULL;