package ca.bc.gov.educ.api.edx.struct.v1;

import ca.bc.gov.educ.api.edx.struct.BaseRequest;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@EqualsAndHashCode(callSuper = true)
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class EdxUserSchoolActivationInviteSagaData extends BaseRequest implements Serializable {
  private static final long serialVersionUID = -7847063658732692951L;
  UUID schoolID;

  String schoolName;
  
  private List<String> edxActivationRoleCodes;

  @Size(max = 255)
  String firstName;

  @Size(max = 255)
  String lastName;

  @Size(max = 255)
  @Email(message = "Email address should be a valid email address")
  String email;

  String edxUserExpiryDate;

  //below fields are generated by the system should not be sent from the UI

  @Null
  String personalActivationCode;
  @Null
  String validationCode;

  @Null
  String edxActivationCodeId;

  @Null
  @JsonDeserialize(using = LocalDateTimeDeserializer.class)
  @JsonSerialize(using = LocalDateTimeSerializer.class)
  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
  LocalDateTime expiryDate;

  String edxUserId;

}
