name: docker-build-push
on:
  workflow_dispatch:

env:
  SPRING_BOOT_IMAGE_NAME: edx-api-master
  DOCKER_ARTIFACTORY_REPO: docker-remote.artifacts.developer.gov.bc.ca
  ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca
jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main
        uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_ARTIFACTORY_REPO }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Spring Boot Image
        id: edx_api_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags:  ${{ env.ARTIFACTORY_REPO }}/artifactory/${{ env.SPRING_BOOT_IMAGE_NAME }}:${{ github.sha }}

#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#
#      - name: Save DigitalOcean kubeconfig with short-lived credentials
#        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-20-2-do-0-blr1-1619022201280
#
#      # Deploy Angular & Spring Boot Docker image to the DigitalOcean kubernetes cluster
#      - name: Deploy
#        run: |-
#          kubectl set image deployment/${{env.ANGULAR_DEPLOYMENT_NAME}} ${{env.ANGULAR_CONTAINER_NAME}}=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.ANGULAR_IMAGE_NAME }}:${{ github.sha }}
#          kubectl set image deployment/${{env.SPRING_BOOT_DEPLOYMENT_NAME}} ${{ env.SPRING_BOOT_CONTAINER_NAME}}=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SPRING_BOOT_IMAGE_NAME }}:${{ github.sha }}
#          kubectl rollout status deployment/${{env.ANGULAR_DEPLOYMENT_NAME}}
#          kubectl rollout status deployment/${{env.SPRING_BOOT_DEPLOYMENT_NAME}}
#          kubectl get services -o wide